# Generated by Django 2.2.6 on 2019-10-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonGames2019',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('away', models.CharField(max_length=30)),
                ('home', models.CharField(max_length=30)),
                ('scores_away', models.IntegerField()),
                ('scores_home', models.IntegerField()),
            ],
            options={
                'db_table': 'season_games_2019',
            },
        ),
        migrations.CreateModel(
            name='GamePredictions2019',
            fields=[
                ('predic_id', models.AutoField(primary_key=True, serialize=False)),
                ('predic_scores_away', models.IntegerField()),
                ('predic_scores_home', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.SeasonGames2019')),
            ],
            options={
                'db_table': 'game_predictions_2019',
            },
        ),
    ]
